### ISSUE TITLE
yap gereksiz yere bash dosyasının içeriğini basıyor

### ISSUE THREAD

**Issue by alimkoca** [themispkg/yap#1]
```
[alimk@manjaro test]$ yap
#!/bin/bash

# Yap Build File Created Automatically by yap 1.0.0

. "/usr/local/lib/bash/5.17/colorsh.sh"
. "/usr/local/lib/bash/5.17/tuiutils.sh"
. "/usr/local/lib/bash/5.17/alternatives.sh"
. "/usr/local/lib/bash/5.17/osutils.sh"
. "/usr/local/lib/bash/5.17/yap/base-utils.sh"

```

**Comment by lazypwny751** [comment]
Yapfile var mı?

**Comment by lazypwny751** [comment]
dostum öncelikle proje daha kullanıcıya sunulma aşamısnda değildir bu nedenden ötürü bu tür durumları bilerek koyuyorum ki kodu daha detaylı inceleyebilmek için. Ayriyeten debian, ubuntu, arch ve opensuse tw dağıtımlarında sorunsuz bir şekilde çalışıyor şu anlık.
