### ISSUE TITLE
yap'ta saymak istemediğim kadar hata var

### ISSUE THREAD

**Issue by alimkoca** [themispkg/yap#2]
Bunları düzeltmeliyiz, bazı yerde basit yazım hataları oluşuyor.

**Comment by lazypwny751** [comment]
Buyrun nedir hata dedikleriniz, proje daha tam olarak yayınlanmadı şu an kullanıma hazır değil ilk sürümü bekleyin

**Comment by lazypwny751** [comment]
şu an ben bir hata göremiyorum projeyi bir de dockerda deneyip dönüş yapacağım.

**Comment by lazypwny751** [comment]
dostum yine dediğim gibi herhangi bir açık göremedim docker ile testini gerçekleştirdim ve olumsuz bir sonuca rastlamadım lakin gözden kaçırmış olabilirim bu durumda pr açmanızı rica ederim onun dışında debian, ubuntu, arch ve opensuse tw'de sorunsuz bir şekilde çalışıyor gözlemlediğim kadarıyla lakin şu an ki sürüm kullanıcıya sunulmak için çok erken gelişmeler için takipte kalın.

**Comment by lazypwny751** [comment]
ek olarak hatadan kastınız yazım hataları, typolar ,grammer hataları vs.. ise şu an ki çıktı kalıcı değildir bu kullanıcıya sunulmadan önce güncellenecektir isterseniz siz de pr açabilirsiniz lakin en son elden geçirilecektir.
